# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gymmie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gymmie
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'gymmieTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gymmie-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gymmie-tvOS

  target 'gymmie-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
